import type { Job } from "./types";

export const dashboardJobs: Job[] = [
  {
    id: 1,
    title: "Senior Next.js developer for a collaborative workspace",
    company: "Northstar Labs",
    verified: true,
    posted: "18 minutes ago",
    type: "Fixed price",
    budget: "$12,000",
    level: "Expert",
    duration: "3–6 months",
    description:
      "We’re looking for an experienced product engineer to help us build real-time collaboration features, improve application performance, and shape a thoughtful frontend architecture.",
    skills: ["Next.js", "TypeScript", "React", "PostgreSQL", "WebSockets"],
    proposals: "Less than 5",
    clientRating: 4.9,
    clientSpent: "$184K spent",
    location: "United States",
    featured: true,
  },
  {
    id: 2,
    title: "Design and build a polished SaaS analytics dashboard",
    company: "Aster Technologies",
    verified: true,
    posted: "42 minutes ago",
    type: "Fixed price",
    budget: "$6,000",
    level: "Intermediate",
    duration: "1–2 months",
    description:
      "Our team has finalized requirements and needs a strong UI engineer who can translate Figma designs into a responsive, accessible dashboard with reusable components.",
    skills: ["React", "Tailwind CSS", "Figma", "Data visualization"],
    proposals: "5 to 10",
    clientRating: 4.8,
    clientSpent: "$92K spent",
    location: "Canada",
  },
  {
    id: 3,
    title: "Full-stack developer for AI-assisted research platform",
    company: "Lumen Research",
    verified: true,
    posted: "1 hour ago",
    type: "Fixed price",
    budget: "$18,500",
    level: "Expert",
    duration: "6+ months",
    description:
      "Join a small senior team building an AI research product. You’ll work across the TypeScript stack and help us design reliable LLM workflows and evaluation tools.",
    skills: ["TypeScript", "Node.js", "OpenAI", "Python", "AWS"],
    proposals: "10 to 15",
    clientRating: 5,
    clientSpent: "$310K spent",
    location: "United Kingdom",
  },
  {
    id: 4,
    title: "Frontend accessibility audit and implementation",
    company: "Commonfolk Studio",
    verified: true,
    posted: "2 hours ago",
    type: "Fixed price",
    budget: "$3,800",
    level: "Expert",
    duration: "Less than 1 month",
    description:
      "Audit our customer portal against WCAG 2.2 AA, document priority issues, and work directly with our engineers to implement and verify the improvements.",
    skills: ["Accessibility", "React", "WCAG", "Testing"],
    proposals: "Less than 5",
    clientRating: 4.9,
    clientSpent: "$76K spent",
    location: "Australia",
  },
];
