import type { AgencyJob } from "./types";

export const agencyJobs: AgencyJob[] = [
  {
    id: 1,
    title: "Product team for a collaborative healthcare workspace",
    company: "Wellmade Health",
    verified: true,
    posted: "16 minutes ago",
    budget: "$38,000",
    budgetValue: 38000,
    level: "Expert",
    duration: "3–6 months",
    description:
      "We are looking for an established product agency to design and build a secure member workspace. The project includes product discovery, interface design, Next.js development, and a production-ready handoff.",
    skills: ["Product design", "Next.js", "TypeScript", "PostgreSQL", "Accessibility"],
    proposals: "Less than 5",
    rating: 4.9,
    spent: "$214K spent",
    location: "United States",
    featured: true,
  },
  {
    id: 2,
    title: "Design and development agency for a SaaS analytics product",
    company: "Orbit Commerce",
    verified: true,
    posted: "38 minutes ago",
    budget: "$52,000",
    budgetValue: 52000,
    level: "Expert",
    duration: "3–6 months",
    description:
      "Our team needs a small senior agency to take an analytics suite from approved requirements through UX, visual design, frontend implementation, and launch support.",
    skills: ["UX/UI", "React", "Data visualization", "Design systems"],
    proposals: "5 to 10",
    rating: 4.8,
    spent: "$126K spent",
    location: "Canada",
  },
  {
    id: 3,
    title: "Engineering team for an AI-assisted research platform",
    company: "Lumen Research",
    verified: true,
    posted: "1 hour ago",
    budget: "$68,500",
    budgetValue: 68500,
    level: "Expert",
    duration: "6+ months",
    description:
      "We want to partner with a technically strong agency that can own the TypeScript application, document ingestion, evaluation workflows, infrastructure, and production quality.",
    skills: ["TypeScript", "Node.js", "OpenAI", "Python", "AWS"],
    proposals: "10 to 15",
    rating: 5,
    spent: "$310K spent",
    location: "United Kingdom",
  },
  {
    id: 4,
    title: "Accessibility remediation and design-system modernization",
    company: "Fieldwork Systems",
    verified: true,
    posted: "2 hours ago",
    budget: "$24,000",
    budgetValue: 24000,
    level: "Intermediate",
    duration: "1–2 months",
    description:
      "Audit our customer platform against WCAG 2.2 AA, remediate priority issues, and modernize the shared React component system with documentation and regression coverage.",
    skills: ["Accessibility", "React", "WCAG", "Storybook", "Testing"],
    proposals: "Less than 5",
    rating: 4.9,
    spent: "$78K spent",
    location: "Australia",
  },
];
