import type { AgencyProposal } from "./types";

export const initialAgencyProposals: AgencyProposal[] = [
  {
    id: 1,
    jobId: 1,
    title: "Design and build a healthcare member portal",
    client: "Wellmade Health",
    status: "Interview",
    submitted: "July 26, 2026",
    clientBudget: "$38,000 fixed",
    agencyBid: "$36,000",
    duration: "14 weeks",
    connects: 16,
    clientRating: "4.9",
    clientSpent: "$214K+ spent",
    activity: "Client sent a message 45 minutes ago",
    coverLetter:
      "Northstar Digital brings senior product design and full-stack engineering together in one compact agency. We can own discovery, interface design, implementation, accessibility, and launch without handoffs between separate vendors.",
    milestonePlan: [
      "Discovery, workflows, and technical architecture",
      "Design system and validated member experience",
      "Application development and integrations",
      "Accessibility verification, launch, and handoff",
    ],
    skills: ["Product design", "Next.js", "TypeScript", "Accessibility"],
  },
  {
    id: 2,
    jobId: 2,
    title: "Product team for commerce analytics suite",
    client: "Orbit Commerce",
    status: "Viewed",
    submitted: "July 25, 2026",
    clientBudget: "$52,000 fixed",
    agencyBid: "$52,000",
    duration: "16 weeks",
    connects: 18,
    clientRating: "4.8",
    clientSpent: "$126K+ spent",
    activity: "Viewed by client 3 hours ago",
    coverLetter:
      "Our agency specializes in complex data products where information architecture, interaction design, and frontend engineering must evolve together. We would begin with a focused product audit before delivering the suite in measurable milestones.",
    milestonePlan: [
      "Product audit and analytics information architecture",
      "Design system and primary dashboard workflows",
      "Frontend implementation and visualization states",
      "QA, documentation, and launch support",
    ],
    skills: ["UX/UI", "React", "Data visualization", "Design systems"],
  },
  {
    id: 3,
    jobId: 3,
    title: "Engineering team for an AI-assisted research platform",
    client: "Lumen Research",
    status: "Submitted",
    submitted: "July 23, 2026",
    clientBudget: "$68,500 fixed",
    agencyBid: "$66,000",
    duration: "24 weeks",
    connects: 20,
    clientRating: "5.0",
    clientSpent: "$310K+ spent",
    activity: "Awaiting client review",
    coverLetter:
      "Northstar Digital combines production TypeScript engineering with applied AI experience. Our approach prioritizes measurable retrieval quality, citations, observability, and maintainable product infrastructure.",
    milestonePlan: [
      "Architecture and evaluation-ready prototype",
      "Document ingestion and citation workflow",
      "Research workspace and collaboration features",
      "Observability, hardening, and production launch",
    ],
    skills: ["TypeScript", "OpenAI", "Python", "PostgreSQL"],
  },
  {
    id: 4,
    jobId: 4,
    title: "Accessibility and design-system modernization",
    client: "Fieldwork Systems",
    status: "Archived",
    submitted: "July 18, 2026",
    clientBudget: "$24,000 fixed",
    agencyBid: "$23,500",
    duration: "8 weeks",
    connects: 14,
    clientRating: "4.9",
    clientSpent: "$78K+ spent",
    activity: "Client selected another agency",
    coverLetter:
      "We proposed a combined WCAG audit, React remediation, component-system modernization, assistive-technology verification, and maintenance documentation.",
    milestonePlan: [
      "Audit and prioritized remediation plan",
      "Component remediation and design-system updates",
      "Verification, regression coverage, and handoff",
    ],
    skills: ["Accessibility", "React", "WCAG", "Storybook"],
  },
];

export const proposalStatusStyles = {
  Interview: "bg-[#e6f2e3] text-[#477344]",
  Viewed: "bg-[#e7eef4] text-[#496c86]",
  Submitted: "bg-[#f1f0e7] text-[#766f47]",
  Archived: "bg-[#f0f1ee] text-[#747971]",
  Withdrawn: "bg-[#f4ebeb] text-[#875e5e]",
} as const;
