import type { AgencyMember } from "./types";

export const initialAgencyMembers: AgencyMember[] = [
  {
    id: 1,
    name: "Shahriar Sajeeb",
    initials: "SK",
    email: "shahriar@northstardigital.io",
    title: "Full-stack product engineer",
    specialty: "Web & software development",
    location: "Chiang Mai, Thailand",
    role: "Agency owner",
    status: "Active",
    joined: "Agency founder",
    profileComplete: 100,
    publicProfile: true,
    skills: ["Next.js", "TypeScript", "Node.js", "PostgreSQL"],
    permissions: [
      "Manage agency profile",
      "Submit proposals",
      "Manage contracts",
      "View finances",
      "Manage members",
    ],
  },
  {
    id: 2,
    name: "Maya Robinson",
    initials: "MR",
    email: "maya@northstardigital.io",
    title: "Senior product designer",
    specialty: "Design & creative",
    location: "New York, USA",
    role: "Business manager",
    status: "Active",
    joined: "Joined May 8, 2026",
    profileComplete: 94,
    publicProfile: true,
    skills: ["Product design", "Figma", "Design systems", "Research"],
    permissions: [
      "Manage agency profile",
      "Submit proposals",
      "Manage contracts",
      "Manage members",
    ],
  },
  {
    id: 3,
    name: "Daniel Cho",
    initials: "DC",
    email: "daniel@northstardigital.io",
    title: "Backend and platform engineer",
    specialty: "Web & software development",
    location: "Toronto, Canada",
    role: "Agency member",
    status: "Active",
    joined: "Joined May 19, 2026",
    profileComplete: 88,
    publicProfile: true,
    skills: ["Node.js", "PostgreSQL", "AWS", "Distributed systems"],
    permissions: [],
  },
  {
    id: 4,
    name: "Amelia Morgan",
    initials: "AM",
    email: "amelia@northstardigital.io",
    title: "Brand strategist",
    specialty: "Marketing",
    location: "London, UK",
    role: "Agency member",
    status: "Active",
    joined: "Joined June 2, 2026",
    profileComplete: 82,
    publicProfile: true,
    skills: ["Brand strategy", "Positioning", "Messaging", "Workshops"],
    permissions: [],
  },
  {
    id: 5,
    name: "Noah Williams",
    initials: "NW",
    email: "noah@example.com",
    title: "Frontend engineer",
    specialty: "Web & software development",
    location: "Lisbon, Portugal",
    role: "Agency member",
    status: "Invitation pending",
    joined: "Invited July 27, 2026",
    profileComplete: 0,
    publicProfile: false,
    skills: ["React", "TypeScript", "Accessibility"],
    permissions: [],
  },
];

export const allAgencyPermissions = [
  "Manage agency profile",
  "Submit proposals",
  "Manage contracts",
  "View finances",
  "Manage members",
] as const;
