import type { DashboardNotification } from "./types";

export const dashboardNotifications: DashboardNotification[] = [
  {
    id: 7,
    icon: "solar:verified-check-linear",
    title: "Identity verification complete",
    description: "Your identity has been confirmed and your account is ready.",
    time: "Just now",
    date: "Today",
    href: "/settings?section=verification",
    category: "Account",
    unread: false,
  },
  {
    id: 1,
    icon: "solar:chat-round-dots-linear",
    title: "New message from Northstar Labs",
    description: "Can you share an update on the notification milestone?",
    time: "8 min ago",
    date: "Today",
    href: "/contracts",
    category: "Messages",
    unread: true,
  },
  {
    id: 2,
    icon: "solar:check-circle-linear",
    title: "Milestone approved",
    description: "Lumen Research approved your architecture milestone.",
    time: "2 hours ago",
    date: "Today",
    href: "/contracts",
    category: "Contracts",
    unread: true,
  },
  {
    id: 3,
    icon: "solar:eye-linear",
    title: "Your proposal was viewed",
    description: "Aster Technologies viewed your dashboard proposal.",
    time: "Yesterday",
    date: "Yesterday",
    href: "/my-proposals",
    category: "Proposals",
    unread: false,
  },
  {
    id: 4,
    icon: "solar:wallet-money-linear",
    title: "Payment released",
    description: "A $3,000 milestone payment from Northstar Labs is now available.",
    time: "Yesterday",
    date: "Yesterday",
    href: "/contracts",
    category: "Payments",
    unread: true,
  },
  {
    id: 5,
    icon: "solar:case-round-linear",
    title: "New contract started",
    description: "Your contract with Commonfolk Studio is now active.",
    time: "July 24",
    date: "Earlier",
    href: "/contracts",
    category: "Contracts",
    unread: false,
  },
  {
    id: 6,
    icon: "solar:chat-round-check-linear",
    title: "Interview invitation",
    description: "Northstar Labs invited you to discuss their collaborative workspace.",
    time: "July 23",
    date: "Earlier",
    href: "/my-proposals",
    category: "Proposals",
    unread: false,
  },
];
